### ISSUE TITLE
Recording comments requires too many confirmations

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/5WoC#1104]
Current workflow:

1. Click the comment button to open the panel to get the Record Comment Button
2. Click the Red Record button
3. Click another Red Record button (a modal for goodness sake)
4. Click Stop
5. Is This OK? Answer Yes
6. Click OK on the Success modal
7. Finally get back to work

It should be:

1. Click the comment button to open the panel to get the Record Comment Button (I guess...)
2. Click the Red Record button and start recording. Animate the Red Record button to indicate recording is happening
3. Click it to stop. All done.

**Comment by Redmayspecial** [comment]
Issue moved to [WycliffeAssociates/translationExchange #428](https://github.com/WycliffeAssociates/translationExchange/issues/428) via [**ZenHub**](https://www.zenhub.com/)
