### ISSUE TITLE
Example User Story_Test

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/5WoC#15]
## User Story
As a translator I would like to use an Android tablet to source from a global langauge, and record in to a target language

## Definition of Done
Using any tablet running with Kit Kat (4.4)
- [x] Joe can edit Definition of Done
- [x] Is this box interactive?

**Comment by zoofries** [comment]
Awesome Sauce with extra MSG, BUDDY! YEEE-HAW!
