### ISSUE TITLE
As an audio recorder, I would like the export page to have a default (and/or recently used) location to export to in order quickly export repeatedly rather than have to navigate every time

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/5WoC#34]
As an audio recorder, I would like the export page to have a default (and/or recently used) location to export to in order quickly export repeatedly rather than have to navigate every time.

J.S.
Be able to confirm whether or not this is possible for SD cards, and if not, prompt user if it could not save.

**Comment by jsarabia1247** [comment]
The default location can be changed, but it cannot be to an SD card. If this is attempted, the app will continue to prompt the user to pick a valid location to save to. 

I suppose this raises the question of whether or not this feature should be allowed at all? If the default location cannot be on an SD card, is it useful to change the save location to be outside of the app's folder?
