### ISSUE TITLE
Research how to save content to Amazon s3 server

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/5WoC#52]
Connect with Jesse regarding the SDK

**Comment by jsarabia1247** [comment]
I need an  Identity Pool ID, bucket name, and region. 

http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/setup.html - Step 3 describes getting AWS credentials
http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/s3transferutility.html - gives a brief tutorial of uploading files
