### ISSUE TITLE
Insert Time Code on Minimap

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/5WoC#53]
## User Story
As a user I would like a timecode on the screen to let me know where I am in the file in order to make editing and jump to a specfic point possible.

## Definition of Done
 - [x] Represent the current time code on the screen while running or at any specific point.

**Comment by Redmayspecial** [comment]
Time-Code represents where you are in the file.  Allows for ease of use when splicing and editing

**Comment by Redmayspecial** [comment]
## Question
Can we have clarification/approval on the timecode on the mini-map and counter based on work done so far.  Joe to insert screenshot or APK

**Comment by jsarabia1247** [comment]
![timecode clarification](https://cloud.githubusercontent.com/assets/9613175/10223795/e76961da-6828-11e5-9e0c-eca199c31cde.jpg)

This is my understanding of what is desired. The major difficulty in this will come from #2, while #1 and #3 seem rather straightforward.

**Comment by jsarabia1247** [comment]
Zenhub apparently associates #number with an issue. I was not intending for that in my previous comment, so please disregard the issues that are linked.
