### ISSUE TITLE
Nexus 9 - Bug Report

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/5WoC#54]
##  Reported Bugs

- [ ] I had the app crash after install using the following steps on my Nexus 9:

     Install APK
     Launch App
    Go to Configuration Screen
    <blam>

    Now it seems fine. Maybe a timeout issue on pulling the JSON files?

**Comment by Redmayspecial** [comment]
Include JSON file with APK

**Comment by jsarabia1247** [comment]
File was already included with APK. The long update time comes from creating a SQL database using the JSON file. The settings page therefore needs to be modified to use the JSON directly.
