### ISSUE TITLE
Can't delete existing files on Nexus 9

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/5WoC#55]

**Comment by Redmayspecial** [comment]
@markalolo What version in your nexus currently at?  4.4?

**Comment by markalolo** [comment]
Android 5.1.1

Kernel version
3.10.40-gbb66a39

Build number LMY48l

<><><><><><><>
Mark Stedman
(407) 852-5416

Innovation happens because there are people out there doing and trying a lot of different things.
-       Edward Felten
