### ISSUE TITLE
Starting Recording/Stopping Recording flashes on the record screen at different times

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/5WoC#59]
Not sure if it's the background service running but I see these labels at odd times.

![screenshot_2015-09-09-15-43-07](https://cloud.githubusercontent.com/assets/12574715/9772458/6b364094-570a-11e5-9364-0c6cec7de9a4.png)

**Comment by PurpleGuitar** [comment]
I think it's primarily for debugging; Joe would probably know whether it's still needed.
